---
abstract: 'Perinci utility routines'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Gen::Test::Rinci::FuncResult: 0
  Perinci::Examples: 0.10
  Test::More: 0.98
  blib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Util
requires:
  Rinci: v1.1.33
  UUID::Random: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Perinci-Util
  repository: http://github.com/sharyanto/perl-Perinci-Util
version: 0.37
